// Comprehensive Purine Database for GoutGuard
// Purine content values are in mg per 100g of food

// ---------------------------------------------------------------------------
// Interfaces
// ---------------------------------------------------------------------------

export interface PurineFood {
  id: string;
  name: string;
  category: string;
  purineContent: number; // mg per 100g
  purineLevel: 'low' | 'moderate' | 'high' | 'very_high';
  description: string;
  servingSize: string;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

export const CATEGORIES = [
  'Meats',
  'Seafood',
  'Vegetables',
  'Dairy',
  'Grains',
  'Beverages',
  'Fruits',
  'Nuts & Seeds',
  'Legumes',
  'Other',
] as const;

export const PURINE_LEVELS = {
  low: { color: '#10b981', label: 'Low', range: '0-100 mg', maxValue: 100 },
  moderate: { color: '#f59e0b', label: 'Moderate', range: '100-200 mg', maxValue: 200 },
  high: { color: '#f97316', label: 'High', range: '200-300 mg', maxValue: 300 },
  very_high: { color: '#ef4444', label: 'Very High', range: '300+ mg', maxValue: Infinity },
} as const;

// ---------------------------------------------------------------------------
// Helper: determine purine level from mg value
// ---------------------------------------------------------------------------

export function getPurineLevel(mg: number): 'low' | 'moderate' | 'high' | 'very_high' {
  if (mg <= 100) return 'low';
  if (mg <= 200) return 'moderate';
  if (mg <= 300) return 'high';
  return 'very_high';
}

// ---------------------------------------------------------------------------
// Purine Database  (80+ foods)
// ---------------------------------------------------------------------------

export const PURINE_DATABASE: PurineFood[] = [
  // ── Very High (300+ mg) ──────────────────────────────────────────────────
  {
    id: 'food_001',
    name: 'Liver (beef)',
    category: 'Meats',
    purineContent: 554,
    purineLevel: 'very_high',
    description: 'Organ meats are among the highest purine foods. Avoid during gout flares.',
    servingSize: '100g',
  },
  {
    id: 'food_002',
    name: 'Kidney (beef)',
    category: 'Meats',
    purineContent: 444,
    purineLevel: 'very_high',
    description: 'Organ meats are extremely high in purines and should be avoided.',
    servingSize: '100g',
  },
  {
    id: 'food_003',
    name: 'Sweetbreads',
    category: 'Meats',
    purineContent: 773,
    purineLevel: 'very_high',
    description: 'Thymus and pancreas glands are very high in purines. Strongly avoid.',
    servingSize: '100g',
  },
  {
    id: 'food_004',
    name: 'Anchovies',
    category: 'Seafood',
    purineContent: 411,
    purineLevel: 'very_high',
    description: 'Very high purine seafood. Common in sauces and dressings — watch for hidden sources.',
    servingSize: '100g',
  },
  {
    id: 'food_005',
    name: 'Sardines',
    category: 'Seafood',
    purineContent: 345,
    purineLevel: 'very_high',
    description: 'High purine content despite being heart-healthy. Limit intake if managing gout.',
    servingSize: '100g',
  },
  {
    id: 'food_006',
    name: 'Herring',
    category: 'Seafood',
    purineContent: 378,
    purineLevel: 'very_high',
    description: 'Very high in purines. Both fresh and pickled forms should be limited.',
    servingSize: '100g',
  },
  {
    id: 'food_007',
    name: 'Mussels',
    category: 'Seafood',
    purineContent: 310,
    purineLevel: 'very_high',
    description: 'Shellfish with very high purine content. Avoid during active gout episodes.',
    servingSize: '100g',
  },
  {
    id: 'food_008',
    name: 'Yeast extract (Marmite)',
    category: 'Other',
    purineContent: 1810,
    purineLevel: 'very_high',
    description: 'Extremely high purine content. Even small amounts can significantly raise uric acid.',
    servingSize: '100g',
  },

  // ── High (200-300 mg) ────────────────────────────────────────────────────
  {
    id: 'food_009',
    name: 'Mackerel',
    category: 'Seafood',
    purineContent: 246,
    purineLevel: 'high',
    description: 'Oily fish with high purine content. Consume in moderation.',
    servingSize: '100g',
  },
  {
    id: 'food_010',
    name: 'Trout',
    category: 'Seafood',
    purineContent: 236,
    purineLevel: 'high',
    description: 'Freshwater fish with high purine levels. Limit portions when managing gout.',
    servingSize: '100g',
  },
  {
    id: 'food_011',
    name: 'Scallops',
    category: 'Seafood',
    purineContent: 222,
    purineLevel: 'high',
    description: 'Shellfish with high purine content. Occasional small servings may be tolerated.',
    servingSize: '100g',
  },
  {
    id: 'food_012',
    name: 'Venison',
    category: 'Meats',
    purineContent: 213,
    purineLevel: 'high',
    description: 'Game meats tend to be high in purines. Limit consumption.',
    servingSize: '100g',
  },
  {
    id: 'food_013',
    name: 'Bacon',
    category: 'Meats',
    purineContent: 232,
    purineLevel: 'high',
    description: 'High in purines and saturated fat. Both factors can worsen gout.',
    servingSize: '100g',
  },
  {
    id: 'food_014',
    name: 'Dried beans',
    category: 'Legumes',
    purineContent: 230,
    purineLevel: 'high',
    description: 'Dried beans are high in purines, though plant purines may have less impact than animal purines.',
    servingSize: '100g',
  },
  {
    id: 'food_015',
    name: 'Beer (per 100ml)',
    category: 'Beverages',
    purineContent: 250,
    purineLevel: 'high',
    description: 'Beer is high in purines AND alcohol inhibits uric acid excretion. Double risk factor for gout.',
    servingSize: '100ml',
  },

  // ── Moderate (100-200 mg) ────────────────────────────────────────────────
  {
    id: 'food_016',
    name: 'Beef',
    category: 'Meats',
    purineContent: 133,
    purineLevel: 'moderate',
    description: 'Moderate purine content. Keep portions small and infrequent.',
    servingSize: '100g',
  },
  {
    id: 'food_017',
    name: 'Pork',
    category: 'Meats',
    purineContent: 145,
    purineLevel: 'moderate',
    description: 'Moderate purine levels. Lean cuts in small portions may be acceptable.',
    servingSize: '100g',
  },
  {
    id: 'food_018',
    name: 'Chicken breast',
    category: 'Meats',
    purineContent: 141,
    purineLevel: 'moderate',
    description: 'Moderate purine content. One of the better meat options for gout management.',
    servingSize: '100g',
  },
  {
    id: 'food_019',
    name: 'Turkey',
    category: 'Meats',
    purineContent: 150,
    purineLevel: 'moderate',
    description: 'Moderate purine levels, similar to chicken. Limit to reasonable portions.',
    servingSize: '100g',
  },
  {
    id: 'food_020',
    name: 'Ham',
    category: 'Meats',
    purineContent: 136,
    purineLevel: 'moderate',
    description: 'Moderate purine content. Processed meats may also be high in sodium.',
    servingSize: '100g',
  },
  {
    id: 'food_021',
    name: 'Salmon',
    category: 'Seafood',
    purineContent: 170,
    purineLevel: 'moderate',
    description: 'Moderate purines but rich in omega-3s which may have anti-inflammatory benefits.',
    servingSize: '100g',
  },
  {
    id: 'food_022',
    name: 'Tuna',
    category: 'Seafood',
    purineContent: 157,
    purineLevel: 'moderate',
    description: 'Moderate purine content. Canned light tuna tends to be slightly lower than fresh.',
    servingSize: '100g',
  },
  {
    id: 'food_023',
    name: 'Crab',
    category: 'Seafood',
    purineContent: 152,
    purineLevel: 'moderate',
    description: 'Moderate purine levels for shellfish. Enjoy in small portions occasionally.',
    servingSize: '100g',
  },
  {
    id: 'food_024',
    name: 'Lobster',
    category: 'Seafood',
    purineContent: 118,
    purineLevel: 'moderate',
    description: 'Lower end of moderate purine shellfish. Small portions may be acceptable.',
    servingSize: '100g',
  },
  {
    id: 'food_025',
    name: 'Shrimp',
    category: 'Seafood',
    purineContent: 147,
    purineLevel: 'moderate',
    description: 'Moderate purine content. Limit portion size and frequency.',
    servingSize: '100g',
  },
  {
    id: 'food_026',
    name: 'Spinach',
    category: 'Vegetables',
    purineContent: 115,
    purineLevel: 'moderate',
    description: 'Moderate purine vegetable, but plant-based purines are less likely to trigger gout.',
    servingSize: '100g',
  },
  {
    id: 'food_027',
    name: 'Asparagus',
    category: 'Vegetables',
    purineContent: 110,
    purineLevel: 'moderate',
    description: 'Moderate purine vegetable. Studies suggest vegetable purines have less gout impact.',
    servingSize: '100g',
  },
  {
    id: 'food_028',
    name: 'Mushrooms',
    category: 'Vegetables',
    purineContent: 120,
    purineLevel: 'moderate',
    description: 'Moderate purine content, but vegetable purines are generally safer for gout.',
    servingSize: '100g',
  },
  {
    id: 'food_029',
    name: 'Lentils',
    category: 'Legumes',
    purineContent: 127,
    purineLevel: 'moderate',
    description: 'Moderate purines but plant-based. Research suggests less gout risk than animal purines.',
    servingSize: '100g',
  },
  {
    id: 'food_030',
    name: 'Peas (green)',
    category: 'Vegetables',
    purineContent: 109,
    purineLevel: 'moderate',
    description: 'Borderline moderate purine content. Generally safe in normal portions.',
    servingSize: '1 cup',
  },
  {
    id: 'food_031',
    name: 'Oatmeal',
    category: 'Grains',
    purineContent: 107,
    purineLevel: 'moderate',
    description: 'Slightly above the low threshold. Generally considered acceptable for gout management.',
    servingSize: '100g',
  },

  // ── Low (0-100 mg) ──────────────────────────────────────────────────────
  {
    id: 'food_032',
    name: 'Eggs',
    category: 'Dairy',
    purineContent: 5,
    purineLevel: 'low',
    description: 'Very low in purines. Excellent protein source for people with gout.',
    servingSize: '100g',
  },
  {
    id: 'food_033',
    name: 'Cheese (cheddar)',
    category: 'Dairy',
    purineContent: 10,
    purineLevel: 'low',
    description: 'Low purine dairy. Dairy products may actually help lower uric acid levels.',
    servingSize: '100g',
  },
  {
    id: 'food_034',
    name: 'Milk',
    category: 'Dairy',
    purineContent: 8,
    purineLevel: 'low',
    description: 'Very low in purines. Low-fat dairy may help reduce gout risk.',
    servingSize: '1 cup',
  },
  {
    id: 'food_035',
    name: 'Yogurt',
    category: 'Dairy',
    purineContent: 8,
    purineLevel: 'low',
    description: 'Very low purine dairy product. May help lower uric acid levels.',
    servingSize: '1 cup',
  },
  {
    id: 'food_036',
    name: 'Butter',
    category: 'Dairy',
    purineContent: 0,
    purineLevel: 'low',
    description: 'No purines. Use in moderation due to saturated fat content.',
    servingSize: '100g',
  },
  {
    id: 'food_037',
    name: 'Cream cheese',
    category: 'Dairy',
    purineContent: 4,
    purineLevel: 'low',
    description: 'Very low in purines. Safe for gout management.',
    servingSize: '100g',
  },
  {
    id: 'food_038',
    name: 'Cottage cheese',
    category: 'Dairy',
    purineContent: 9,
    purineLevel: 'low',
    description: 'Low purine, high protein dairy. Good option for gout-friendly meals.',
    servingSize: '100g',
  },
  {
    id: 'food_039',
    name: 'Ice cream',
    category: 'Dairy',
    purineContent: 10,
    purineLevel: 'low',
    description: 'Low in purines but high in sugar. Consume in moderation.',
    servingSize: '100g',
  },
  {
    id: 'food_040',
    name: 'Bread (white)',
    category: 'Grains',
    purineContent: 18,
    purineLevel: 'low',
    description: 'Low purine grain product. Refined grains are generally lower in purines.',
    servingSize: '100g',
  },
  {
    id: 'food_041',
    name: 'Rice (white)',
    category: 'Grains',
    purineContent: 25,
    purineLevel: 'low',
    description: 'Low purine staple grain. Safe for regular consumption.',
    servingSize: '100g',
  },
  {
    id: 'food_042',
    name: 'Pasta',
    category: 'Grains',
    purineContent: 22,
    purineLevel: 'low',
    description: 'Low purine grain product. A good base for gout-friendly meals.',
    servingSize: '100g',
  },
  {
    id: 'food_043',
    name: 'Potatoes',
    category: 'Vegetables',
    purineContent: 16,
    purineLevel: 'low',
    description: 'Low purine vegetable. Versatile and safe for gout-friendly diets.',
    servingSize: '100g',
  },
  {
    id: 'food_044',
    name: 'Carrots',
    category: 'Vegetables',
    purineContent: 8,
    purineLevel: 'low',
    description: 'Very low in purines. Nutrient-rich and safe for unlimited consumption.',
    servingSize: '100g',
  },
  {
    id: 'food_045',
    name: 'Lettuce',
    category: 'Vegetables',
    purineContent: 12,
    purineLevel: 'low',
    description: 'Very low purine content. Great base for salads.',
    servingSize: '100g',
  },
  {
    id: 'food_046',
    name: 'Tomatoes',
    category: 'Vegetables',
    purineContent: 11,
    purineLevel: 'low',
    description: 'Low in purines. Despite anecdotal reports, tomatoes are generally safe for gout.',
    servingSize: '100g',
  },
  {
    id: 'food_047',
    name: 'Corn',
    category: 'Vegetables',
    purineContent: 32,
    purineLevel: 'low',
    description: 'Low purine content. Safe for regular consumption.',
    servingSize: '100g',
  },
  {
    id: 'food_048',
    name: 'Cucumber',
    category: 'Vegetables',
    purineContent: 7,
    purineLevel: 'low',
    description: 'Very low in purines and high in water content. Helps with hydration.',
    servingSize: '100g',
  },
  {
    id: 'food_049',
    name: 'Bell peppers',
    category: 'Vegetables',
    purineContent: 12,
    purineLevel: 'low',
    description: 'Low purine and high in vitamin C, which may help lower uric acid.',
    servingSize: '100g',
  },
  {
    id: 'food_050',
    name: 'Onions',
    category: 'Vegetables',
    purineContent: 13,
    purineLevel: 'low',
    description: 'Low in purines. Adds flavour to gout-friendly meals.',
    servingSize: '100g',
  },
  {
    id: 'food_051',
    name: 'Celery',
    category: 'Vegetables',
    purineContent: 18,
    purineLevel: 'low',
    description: 'Low purine content with high water content. Beneficial for hydration.',
    servingSize: '100g',
  },
  {
    id: 'food_052',
    name: 'Broccoli',
    category: 'Vegetables',
    purineContent: 70,
    purineLevel: 'low',
    description: 'Low-to-moderate purine vegetable. Rich in vitamin C which may benefit gout.',
    servingSize: '100g',
  },
  {
    id: 'food_053',
    name: 'Cauliflower',
    category: 'Vegetables',
    purineContent: 51,
    purineLevel: 'low',
    description: 'Low purine vegetable. Safe for regular consumption.',
    servingSize: '100g',
  },
  {
    id: 'food_054',
    name: 'Cabbage',
    category: 'Vegetables',
    purineContent: 22,
    purineLevel: 'low',
    description: 'Low in purines. A nutritious vegetable safe for gout diets.',
    servingSize: '100g',
  },
  {
    id: 'food_055',
    name: 'Sweet potato',
    category: 'Vegetables',
    purineContent: 25,
    purineLevel: 'low',
    description: 'Low purine content with excellent nutritional value.',
    servingSize: '100g',
  },
  {
    id: 'food_056',
    name: 'Bananas',
    category: 'Fruits',
    purineContent: 16,
    purineLevel: 'low',
    description: 'Low in purines and rich in potassium. Good snack for gout management.',
    servingSize: '100g',
  },
  {
    id: 'food_057',
    name: 'Apples',
    category: 'Fruits',
    purineContent: 14,
    purineLevel: 'low',
    description: 'Low purine fruit. Safe for regular consumption.',
    servingSize: '100g',
  },
  {
    id: 'food_058',
    name: 'Oranges',
    category: 'Fruits',
    purineContent: 19,
    purineLevel: 'low',
    description: 'Low in purines and high in vitamin C, which may help reduce uric acid.',
    servingSize: '100g',
  },
  {
    id: 'food_059',
    name: 'Strawberries',
    category: 'Fruits',
    purineContent: 21,
    purineLevel: 'low',
    description: 'Low purine fruit with antioxidant benefits.',
    servingSize: '100g',
  },
  {
    id: 'food_060',
    name: 'Cherries',
    category: 'Fruits',
    purineContent: 17,
    purineLevel: 'low',
    description: 'Low in purines. Studies suggest cherries may help reduce gout flares and lower uric acid.',
    servingSize: '100g',
  },
  {
    id: 'food_061',
    name: 'Almonds',
    category: 'Nuts & Seeds',
    purineContent: 37,
    purineLevel: 'low',
    description: 'Low purine nut. Good source of healthy fats and protein.',
    servingSize: '100g',
  },
  {
    id: 'food_062',
    name: 'Walnuts',
    category: 'Nuts & Seeds',
    purineContent: 44,
    purineLevel: 'low',
    description: 'Low purine nut rich in omega-3 fatty acids.',
    servingSize: '100g',
  },
  {
    id: 'food_063',
    name: 'Peanuts',
    category: 'Nuts & Seeds',
    purineContent: 79,
    purineLevel: 'low',
    description: 'Low purine content. A good protein alternative to meat.',
    servingSize: '100g',
  },
  {
    id: 'food_064',
    name: 'Tofu',
    category: 'Legumes',
    purineContent: 68,
    purineLevel: 'low',
    description: 'Low purine plant protein. Soy-based foods are generally safe for gout.',
    servingSize: '100g',
  },
  {
    id: 'food_065',
    name: 'Coffee',
    category: 'Beverages',
    purineContent: 10,
    purineLevel: 'low',
    description: 'Low in purines. Research suggests regular coffee consumption may help lower uric acid levels.',
    servingSize: '100ml',
  },
  {
    id: 'food_066',
    name: 'Tea',
    category: 'Beverages',
    purineContent: 8,
    purineLevel: 'low',
    description: 'Very low in purines. Safe beverage for gout management.',
    servingSize: '100ml',
  },
  {
    id: 'food_067',
    name: 'Water',
    category: 'Beverages',
    purineContent: 0,
    purineLevel: 'low',
    description: 'No purines. Staying well-hydrated helps flush uric acid from the body.',
    servingSize: '100ml',
  },
  {
    id: 'food_068',
    name: 'Chocolate (dark)',
    category: 'Other',
    purineContent: 30,
    purineLevel: 'low',
    description: 'Low purine content. Enjoy in moderation as part of a balanced diet.',
    servingSize: '100g',
  },
  {
    id: 'food_069',
    name: 'Honey',
    category: 'Other',
    purineContent: 4,
    purineLevel: 'low',
    description: 'Very low in purines. High in fructose though, which may affect uric acid in excess.',
    servingSize: '100g',
  },
  {
    id: 'food_070',
    name: 'Olive oil',
    category: 'Other',
    purineContent: 0,
    purineLevel: 'low',
    description: 'No purines. A heart-healthy fat recommended for gout-friendly cooking.',
    servingSize: '100ml',
  },
  {
    id: 'food_071',
    name: 'Vinegar',
    category: 'Other',
    purineContent: 2,
    purineLevel: 'low',
    description: 'Virtually no purines. Apple cider vinegar is often cited in folk remedies for gout.',
    servingSize: '100ml',
  },
  {
    id: 'food_072',
    name: 'Wine (red, per 100ml)',
    category: 'Beverages',
    purineContent: 13,
    purineLevel: 'low',
    description: 'Low in purines but alcohol still raises uric acid. Limit to one glass or less per day.',
    servingSize: '100ml',
  },
  {
    id: 'food_073',
    name: 'Whiskey/spirits (per 100ml)',
    category: 'Beverages',
    purineContent: 0,
    purineLevel: 'low',
    description: 'No purines, but alcohol metabolism still raises uric acid by reducing kidney excretion.',
    servingSize: '100ml',
  },

  // ── Additional foods to reach 80+ entries ────────────────────────────────
  {
    id: 'food_074',
    name: 'Lamb',
    category: 'Meats',
    purineContent: 182,
    purineLevel: 'moderate',
    description: 'Moderate purine content. Choose lean cuts and limit portion sizes.',
    servingSize: '100g',
  },
  {
    id: 'food_075',
    name: 'Duck',
    category: 'Meats',
    purineContent: 165,
    purineLevel: 'moderate',
    description: 'Moderate purine levels. Remove skin to reduce fat intake.',
    servingSize: '100g',
  },
  {
    id: 'food_076',
    name: 'Sausage (pork)',
    category: 'Meats',
    purineContent: 198,
    purineLevel: 'moderate',
    description: 'Upper-moderate purine content. Processed meats may also be high in sodium.',
    servingSize: '100g',
  },
  {
    id: 'food_077',
    name: 'Liver (chicken)',
    category: 'Meats',
    purineContent: 345,
    purineLevel: 'very_high',
    description: 'Organ meats are very high in purines regardless of the animal source.',
    servingSize: '100g',
  },
  {
    id: 'food_078',
    name: 'Oysters',
    category: 'Seafood',
    purineContent: 240,
    purineLevel: 'high',
    description: 'High purine shellfish. Avoid during gout flares.',
    servingSize: '100g',
  },
  {
    id: 'food_079',
    name: 'Squid (calamari)',
    category: 'Seafood',
    purineContent: 135,
    purineLevel: 'moderate',
    description: 'Moderate purine content. Fried preparations add extra inflammatory risk.',
    servingSize: '100g',
  },
  {
    id: 'food_080',
    name: 'Cod',
    category: 'Seafood',
    purineContent: 109,
    purineLevel: 'moderate',
    description: 'Lower-moderate purine white fish. Better option than oily fish for gout.',
    servingSize: '100g',
  },
  {
    id: 'food_081',
    name: 'Grapes',
    category: 'Fruits',
    purineContent: 10,
    purineLevel: 'low',
    description: 'Low in purines. A safe and nutritious fruit for gout-friendly diets.',
    servingSize: '100g',
  },
  {
    id: 'food_082',
    name: 'Watermelon',
    category: 'Fruits',
    purineContent: 8,
    purineLevel: 'low',
    description: 'Very low in purines and high in water content. Helps with hydration.',
    servingSize: '100g',
  },
  {
    id: 'food_083',
    name: 'Pineapple',
    category: 'Fruits',
    purineContent: 15,
    purineLevel: 'low',
    description: 'Low purine fruit. Contains bromelain which may have anti-inflammatory properties.',
    servingSize: '100g',
  },
  {
    id: 'food_084',
    name: 'Blueberries',
    category: 'Fruits',
    purineContent: 19,
    purineLevel: 'low',
    description: 'Low in purines and rich in antioxidants. Excellent for an anti-inflammatory diet.',
    servingSize: '100g',
  },
  {
    id: 'food_085',
    name: 'Chickpeas',
    category: 'Legumes',
    purineContent: 109,
    purineLevel: 'moderate',
    description: 'Moderate purine content. Plant purines may have less impact on gout than animal purines.',
    servingSize: '100g',
  },
  {
    id: 'food_086',
    name: 'Kidney beans',
    category: 'Legumes',
    purineContent: 143,
    purineLevel: 'moderate',
    description: 'Moderate purine content. Soaking and cooking reduces purine levels somewhat.',
    servingSize: '100g',
  },
  {
    id: 'food_087',
    name: 'Sunflower seeds',
    category: 'Nuts & Seeds',
    purineContent: 65,
    purineLevel: 'low',
    description: 'Low purine snack. Good source of vitamin E and healthy fats.',
    servingSize: '100g',
  },
  {
    id: 'food_088',
    name: 'Flaxseeds',
    category: 'Nuts & Seeds',
    purineContent: 55,
    purineLevel: 'low',
    description: 'Low purine content with anti-inflammatory omega-3 fatty acids.',
    servingSize: '100g',
  },
  {
    id: 'food_089',
    name: 'Quinoa',
    category: 'Grains',
    purineContent: 75,
    purineLevel: 'low',
    description: 'Low purine pseudocereal. Complete protein source for gout-friendly diets.',
    servingSize: '100g',
  },
  {
    id: 'food_090',
    name: 'Brown rice',
    category: 'Grains',
    purineContent: 38,
    purineLevel: 'low',
    description: 'Low purine whole grain. Slightly higher than white rice but still safe.',
    servingSize: '100g',
  },
  {
    id: 'food_091',
    name: 'Whole wheat bread',
    category: 'Grains',
    purineContent: 42,
    purineLevel: 'low',
    description: 'Low purine content. Whole grains provide additional fiber and nutrients.',
    servingSize: '100g',
  },
  {
    id: 'food_092',
    name: 'Zucchini',
    category: 'Vegetables',
    purineContent: 15,
    purineLevel: 'low',
    description: 'Very low purine vegetable. Versatile and safe for gout diets.',
    servingSize: '100g',
  },
  {
    id: 'food_093',
    name: 'Eggplant',
    category: 'Vegetables',
    purineContent: 21,
    purineLevel: 'low',
    description: 'Low in purines. A great meat substitute in many recipes.',
    servingSize: '100g',
  },
  {
    id: 'food_094',
    name: 'Garlic',
    category: 'Vegetables',
    purineContent: 15,
    purineLevel: 'low',
    description: 'Low purine content with potential anti-inflammatory benefits.',
    servingSize: '100g',
  },
  {
    id: 'food_095',
    name: 'Ginger',
    category: 'Other',
    purineContent: 9,
    purineLevel: 'low',
    description: 'Very low in purines. Has natural anti-inflammatory properties that may help with gout.',
    servingSize: '100g',
  },
  {
    id: 'food_096',
    name: 'Turmeric',
    category: 'Other',
    purineContent: 12,
    purineLevel: 'low',
    description: 'Low purine spice. Curcumin may have anti-inflammatory benefits for gout.',
    servingSize: '100g',
  },
  {
    id: 'food_097',
    name: 'Orange juice',
    category: 'Beverages',
    purineContent: 11,
    purineLevel: 'low',
    description: 'Low in purines but high in fructose. Excessive fructose may raise uric acid.',
    servingSize: '100ml',
  },
  {
    id: 'food_098',
    name: 'Soda (cola)',
    category: 'Beverages',
    purineContent: 0,
    purineLevel: 'low',
    description: 'No purines, but high fructose corn syrup can increase uric acid production.',
    servingSize: '100ml',
  },
  {
    id: 'food_099',
    name: 'Mango',
    category: 'Fruits',
    purineContent: 12,
    purineLevel: 'low',
    description: 'Low purine tropical fruit. Rich in vitamins A and C.',
    servingSize: '100g',
  },
  {
    id: 'food_100',
    name: 'Avocado',
    category: 'Fruits',
    purineContent: 19,
    purineLevel: 'low',
    description: 'Low in purines with heart-healthy monounsaturated fats.',
    servingSize: '100g',
  },
];

// ---------------------------------------------------------------------------
// Search & Filter Helpers
// ---------------------------------------------------------------------------

/**
 * Search foods by name query, optionally filtering by category and/or purine level.
 */
export function searchFoods(
  query: string,
  category?: string,
  level?: string,
): PurineFood[] {
  const lowerQuery = query.toLowerCase().trim();

  return PURINE_DATABASE.filter((food) => {
    const matchesQuery = lowerQuery === '' || food.name.toLowerCase().includes(lowerQuery);
    const matchesCategory = !category || food.category === category;
    const matchesLevel = !level || food.purineLevel === level;
    return matchesQuery && matchesCategory && matchesLevel;
  });
}

/**
 * Get all foods belonging to a specific category.
 */
export function getFoodsByCategory(category: string): PurineFood[] {
  return PURINE_DATABASE.filter((food) => food.category === category);
}

/**
 * Get all foods at a specific purine level.
 */
export function getFoodsByLevel(level: string): PurineFood[] {
  return PURINE_DATABASE.filter((food) => food.purineLevel === level);
}
