require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '16.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# temporary de-interating each Xcode pod project
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCamera', :path => '../../node_modules/@capacitor/camera'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/@capacitor/local-notifications'
  pod 'CapacitorPushNotifications', :path => '../../node_modules/@capacitor/push-notifications'
  pod 'CapgoNativePurchases', :path => '../../node_modules/@capgo/native-purchases'
end

target 'App' do
  capacitor_pods
  # Cordova plugins for StoreKit support
  pod 'CordovaPlugins', :path => '../../capacitor-cordova-ios-plugins'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
