import SwiftUI

// MARK: - Disclaimer / Terms of Use

struct DisclaimerView: View {
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                legalSection(title: "Medical Disclaimer", content: """
                KidneyCare+ is designed for informational and educational purposes only. The information provided by this application should not be considered as medical advice, diagnosis, or treatment recommendations.

                This app is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician, transplant team, or other qualified health provider with any questions you may have regarding a medical condition or dietary choices.

                Never disregard professional medical advice or delay in seeking it because of information provided by this application. If you think you may have a medical emergency, call your doctor or emergency services immediately.
                """)

                legalSection(title: "Limitation of Liability", content: """
                KIDNEYCARE+ and its developers shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use this application.

                The nutritional analysis provided is generated by artificial intelligence and may not be 100% accurate. Always verify results with your healthcare provider.
                """)

                legalSection(title: "Age Requirement", content: """
                You must be at least 17 years of age to use this App. By using the App, you represent and warrant that you meet this age requirement.
                """)

                legalSection(title: "Contact", content: """
                For questions about this disclaimer, contact us at support@kidneycare.app
                """)

                // Medical Sources & Citations
                VStack(alignment: .leading, spacing: 10) {
                    Text("Medical Sources & Citations")
                        .font(.headline)
                        .foregroundColor(AppTheme.text)

                    Text("The health information in this app is based on the following published medical sources:")
                        .font(.subheadline)
                        .foregroundColor(AppTheme.textLight)
                        .lineSpacing(3)

                    citationItem(
                        number: "1",
                        text: "Blood Pressure Categories — American Heart Association (AHA). \"Understanding Blood Pressure Readings.\"",
                        url: "https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings"
                    )
                    citationItem(
                        number: "2",
                        text: "Blood Glucose Levels — American Diabetes Association (ADA). \"Understanding A1C\" and \"Diabetes Diagnosis.\"",
                        url: "https://diabetes.org/about-diabetes/diagnosis"
                    )
                    citationItem(
                        number: "3",
                        text: "Grapefruit-Drug Interactions — U.S. Food & Drug Administration (FDA). \"Grapefruit Juice and Some Drugs Don't Mix.\"",
                        url: "https://www.fda.gov/consumers/consumer-updates/grapefruit-juice-and-some-drugs-dont-mix"
                    )
                    citationItem(
                        number: "4",
                        text: "Nutrition for Kidney Transplant — National Kidney Foundation (NKF). \"Nutrition and Transplantation.\"",
                        url: "https://www.kidney.org/nutrition-kidney-transplant"
                    )
                    citationItem(
                        number: "5",
                        text: "Post-Transplant Dietary Guidelines — Kidney Disease: Improving Global Outcomes (KDIGO). \"Clinical Practice Guideline for the Care of Kidney Transplant Recipients.\"",
                        url: "https://kdigo.org/guidelines/transplant-recipient/"
                    )
                    citationItem(
                        number: "6",
                        text: "Food Safety for Immunocompromised — U.S. Department of Health and Human Services. \"Food Safety for People with Weakened Immune Systems.\"",
                        url: "https://www.foodsafety.gov/people-at-risk/people-with-weakened-immune-systems"
                    )
                    citationItem(
                        number: "7",
                        text: "Sodium Intake Recommendation — American Heart Association (AHA). \"How Much Sodium Should I Eat Per Day?\"",
                        url: "https://www.heart.org/en/healthy-living/healthy-eating/eat-smart/sodium/how-much-sodium-should-i-eat-per-day"
                    )
                    citationItem(
                        number: "8",
                        text: "Immunosuppressant Medications — Organ Procurement and Transplantation Network (OPTN/UNOS). \"What Every Patient Needs to Know.\"",
                        url: "https://optn.transplant.hrsa.gov/patients/"
                    )
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding()
                .background(AppTheme.card)
                .cornerRadius(12)
            }
            .padding()
        }
        .background(AppTheme.background)
        .navigationTitle("Terms of Use")
        .navigationBarTitleDisplayMode(.inline)
    }
}

// MARK: - Privacy Policy

struct PrivacyView: View {
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                legalSection(title: "Privacy Policy", content: """
                Last updated: February 2026

                KidneyCare+ ("we", "our", or "the App") is committed to protecting your privacy. This Privacy Policy explains how we handle information when you use our application.
                """)

                legalSection(title: "Information We Collect", content: """
                Images: When you use the food scanner feature, images are sent to our server for analysis using AI. Images are processed in real-time and are not stored on our servers after analysis is complete.

                Health Data: Blood pressure readings, glucose readings, medication lists, and meal favorites are stored locally on your device only. We do not collect, transmit, or store your health data on any server.

                Purchase Information: In-app purchase transactions are processed entirely by Apple through the App Store. We do not collect or store any payment information.
                """)

                legalSection(title: "Data Storage", content: """
                All personal health data (vitals, medications, favorites) is stored locally on your device using encrypted storage. This data never leaves your device except for:

                • Nutrition label images sent for AI analysis (not stored after processing)
                • Meal recommendation requests (no personal data included)
                """)

                legalSection(title: "Third-Party Services", content: """
                We use Anthropic's Claude AI for nutrition analysis and meal recommendations. Only the images you submit and meal type preferences are sent to this service. No personal health data is shared.
                """)

                legalSection(title: "Your Rights", content: """
                You can delete all your data at any time by uninstalling the app. Since all health data is stored locally on your device, uninstalling completely removes all your information.
                """)

                legalSection(title: "Contact", content: """
                For privacy-related questions, contact us at support@kidneycare.app
                """)
            }
            .padding()
        }
        .background(AppTheme.background)
        .navigationTitle("Privacy Policy")
        .navigationBarTitleDisplayMode(.inline)
    }
}

// MARK: - Support

struct SupportView: View {
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                legalSection(title: "Contact Us", content: """
                If you need help with KidneyCare+, have questions, or want to report a problem, please reach out to our support team:

                Email: support@kidneycare.app

                We aim to respond to all support requests within 24–48 hours.
                """)

                legalSection(title: "Frequently Asked Questions", content: "")

                faqItem(question: "How does the food scanner work?", answer: """
                Take a photo of a nutrition label or ingredients list, and our AI analyzes it for safety considerations specific to post-kidney transplant patients. The analysis checks for high sodium, potassium, phosphorus, and other nutrients that may need monitoring after a transplant.
                """)

                faqItem(question: "Is KidneyCare+ a substitute for medical advice?", answer: """
                No. KidneyCare+ is for informational purposes only. Always consult your transplant care team, dietitian, or healthcare provider before making dietary changes.
                """)

                faqItem(question: "How do I unlock Meal Recommendations or Health Vitals?", answer: """
                These are premium features available as one-time in-app purchases. Open the Meal Recommendations or Health Vitals section and tap the unlock button. If you've already purchased, tap "Restore Purchase" to recover your access.
                """)

                faqItem(question: "I purchased a feature but lost access. What should I do?", answer: """
                Go to the feature page and tap "Restore Purchase." This will check your Apple ID for previous purchases and restore your access. If the issue persists, contact us at support@kidneycare.app.
                """)

                faqItem(question: "Can I get a refund?", answer: """
                In-app purchases are processed by Apple. To request a refund, visit reportaproblem.apple.com and follow the instructions for your purchase.
                """)

                faqItem(question: "Is my data stored securely?", answer: """
                Yes. All your health data is stored locally on your device. We do not collect, store, or share your personal health information on any server.
                """)

                faqItem(question: "What devices are supported?", answer: """
                KidneyCare+ requires iOS 16.0 or later and works on iPhone and iPad.
                """)

                legalSection(title: "Report a Bug", content: """
                If you encounter a bug, please email support@kidneycare.app with:

                • Your device model and iOS version
                • A description of the issue
                • Steps to reproduce the problem
                • Screenshots if applicable
                """)
            }
            .padding()
        }
        .background(AppTheme.background)
        .navigationTitle("Support")
        .navigationBarTitleDisplayMode(.inline)
    }
}

// MARK: - Helper Views

private func legalSection(title: String, content: String) -> some View {
    VStack(alignment: .leading, spacing: 6) {
        Text(title)
            .font(.headline)
            .foregroundColor(AppTheme.text)
        if !content.isEmpty {
            Text(content)
                .font(.subheadline)
                .foregroundColor(AppTheme.textLight)
                .lineSpacing(4)
        }
    }
    .frame(maxWidth: .infinity, alignment: .leading)
    .padding()
    .background(AppTheme.card)
    .cornerRadius(12)
}

private func faqItem(question: String, answer: String) -> some View {
    VStack(alignment: .leading, spacing: 6) {
        Text(question)
            .font(.subheadline.bold())
            .foregroundColor(AppTheme.text)
        Text(answer)
            .font(.caption)
            .foregroundColor(AppTheme.textLight)
            .lineSpacing(3)
    }
    .frame(maxWidth: .infinity, alignment: .leading)
    .padding()
    .background(AppTheme.card)
    .cornerRadius(12)
}

private func citationItem(number: String, text: String, url: String) -> some View {
    VStack(alignment: .leading, spacing: 2) {
        Text("[\(number)] \(text)")
            .font(.caption)
            .foregroundColor(AppTheme.textLight)
            .lineSpacing(2)
        if let link = URL(string: url) {
            Link(url, destination: link)
                .font(.caption2)
                .foregroundColor(AppTheme.primary)
                .lineLimit(1)
                .truncationMode(.middle)
        }
    }
    .padding(.vertical, 4)
}
